name: Mod Request
description: Request a mod
title: "[MOD REQUEST]"
labels: ["mod-request"]
assignees: [""]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this mod request!
  - type: input
    id: mod-name
    attributes:
      label: Mod Name
      description: Please enter the name of the mod you're requesting.
    validations:
      required: true
  - type: input
    id: mod-link
    attributes:
      label: Mod Link
      description: Please enter the link to the mod.
    validations:
      required: true
